<?php

module_load_include('inc', 'os2forms_doc', 'includes/os2forms_doc.utils');

/**
 * Implements hook_mail_alter().
 */
function os2forms_doc_mail_alter(&$message) {
  if (($message['id'] == 'webform_submission') && isset($message['params']['node']) && isset($message['params']['submission'])) {
    $node = $message['params']['node'];
    $submission = $message['params']['submission'];

    $attachments = array();

    // Generate DOC config.
    $generate_doc_config = os2forms_frontend_webform_get_setting($node->nid, 'os2forms_doc');
    if (isset($generate_doc_config) && $generate_doc_config['enabled']) {
      // Creating a file in a temporary dir.
      $file_uri = os2forms_doc_create_file($node, $submission);
      $file_size = filesize($file_uri);
      $handle = fopen($file_uri, "rb");
      $content = fread($handle, $file_size);
      fclose($handle);

      $attachment = new stdClass;
      $attachment->filecontent = $content;
      $attachment->filename = basename($file_uri);
      $attachment->filemime = mime_content_type($file_uri);

      $attachments[] = $attachment;

      // Deleting the file in the end.
      file_unmanaged_delete($file_uri);
    }

    if (!empty($attachments)) {
      $html_capable = variable_get('webform_email_html_capable', FALSE);

      if ($html_capable) {
        if (module_exists('mimemail')) {
          foreach($attachments as $attachment) {
            $message['params']['attachments'][] = $attachment;
          }
        }
      }
      else {
        foreach($attachments as $attachment) {
          //find existing trenner
          preg_match('/\multipart\/mixed;\ boundary=\"(.*)\"/', $message['headers']['Content-Type'], $matches);
          $trenner = $matches[1];

          //remove message end
          $message['body'][0] = str_replace("--$trenner--", '', $message['body'][0]);

          //and new content
          $message['body'][0] .= "\n\n--" . $trenner . "\n";
          $message['body'][0] .= "Content-Type: " . $attachment->filemime . "; name=\"" . $attachment->filename . "\"\n";
          $message['body'][0] .= "Content-Transfer-Encoding: base64\n";
          $message['body'][0] .= "Content-Disposition: attachment; filename=\"" . $attachment->filename . "\"\n\n";
          $message['body'][0] .= chunk_split(base64_encode($attachment->filecontent));
          $message['body'][0] .= "\n\n";
          $message['body'][0] .= "--" . $trenner . "--";
        }
      }
    }
  }
}
